<?php

namespace Amulen\MediaBundle\Repository;

use Flowcode\MediaBundle\Repository\MediaRepository as BaseMediaRepository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends BaseMediaRepository
{
}
