<?php

namespace Amulen\PageBundle\Repository;

use Flowcode\PageBundle\Repository\BlockRepository as BaseBlockRepository;

/**
 * BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRepository extends BaseBlockRepository
{
}
