<?php

namespace Amulen\PageBundle\Repository;

use Flowcode\PageBundle\Repository\MenuItemLabelRepository as BaseMenuItemLabelRepository;

/**
 * MenuItemLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemLabelRepository extends BaseMenuItemLabelRepository
{
}
