<?php

namespace Amulen\PageBundle\Repository;

use Flowcode\PageBundle\Repository\MenuRepository as BaseMenuRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends BaseMenuRepository
{
}
