<?php

namespace Amulen\PageBundle\Repository;

use Flowcode\PageBundle\Repository\MenuItemRepository as BaseMenuItemRepository;

/**
 * MenuItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemRepository extends BaseMenuItemRepository
{
}
