<?php

namespace Amulen\PageBundle\Repository;

use Flowcode\PageBundle\Repository\PageRepository as BasePageRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends BasePageRepository
{
}
