<?php

namespace Amulen\ShopBundle\Repository;

use Flowcode\ShopBundle\Repository\BrandRepository as BaseBrandRepository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends BaseBrandRepository
{
}
