<?php

namespace Amulen\ShopBundle\Repository;

use Flowcode\ShopBundle\Repository\CategoryRepository as BaseCategoryRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends BaseCategoryRepository
{
}
