# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Amulen\UserBundle\Entity\User:
            algorithm: sha1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        user_db:
            id: "flowcode.user"

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        backend:
            pattern: ^/admin
            form_login:
               provider: user_db
               login_path: flowcode_admin_user_login
               check_path: flowcode_admin_user_check
               always_use_default_target_path: true
               default_target_path: admin_dashboard
               use_referer: true
            logout:
               path: flowcode_admin_user_logout
               target: flowcode_admin_user_login
            anonymous:    true

        main:
            anonymous: ~


    access_control:
       - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/admin/login/forgot, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/admin/, role: ROLE_ADMIN }
