<?php

namespace Amulen\ClassificationBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Flowcode\ClassificationBundle\Repository\CollectionRepository as BaseCollectionRepository;

/**
 * CollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionRepository extends BaseCollectionRepository
{
}
