<?php

namespace Amulen\ClassificationBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Flowcode\ClassificationBundle\Repository\TagRepository as BaseTagRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends BaseTagRepository
{
}
